name: Build Latest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Build Package Source
      run: |
        yarn install
        yarn build

    - name: Git push assets to "release" branch
      run: |
        echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        cd dist
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b release
        git add .
        git commit -m "${{ env.RELEASE_NAME }}"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin release
